{
 "title": "Pertisk Eproxy Dashboard",
 "tags": [
  "Website",
  "hub-style"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_ds", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Mode",
    "query": "label_values({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\"}, job)"
   },
   {
    "name": "filename",
    "label": "Filename",
    "query": "label_values({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\"}, filename)"
   },
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\"}, site)"
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "label_values(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\"}, proto)"
   }
  ]
 },
 "panels": [
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\"}[$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Visitor per Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | unwrap bytes_sent | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Request per status code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\"}[$__interval]))",
     "legendFormat": "HTTP status: {{status}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | status != \"\" [$__interval]))",
     "legendFormat": "status: {{status}}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | method != \"\" [$__interval]))",
     "legendFormat": "Method: {{method}}"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(proto) (rate(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\"}[$__rate_interval]))",
     "legendFormat": "Protocol: {{proto}}"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(compression) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\"  [$__interval]))",
     "legendFormat": "Compression: {{compression}}"
    }
   ]
  },
  {
   "title": "Status in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | status != \"\" [$__interval]))",
     "legendFormat": "status: {{status}}"
    }
   ]
  },
  {
   "title": "Methods in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | method != \"\" [$__interval]))",
     "legendFormat": "Method: {{method}}"
    }
   ]
  },
  {
   "title": "Browsers in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum by(http_user_agent) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | http_user_agent != \"\" [$__interval]))",
     "legendFormat": "Browser: {{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Top Websites",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | host != \"\" [$__interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Bad requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top (bad) IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 401 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 403 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 404 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 400 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 500 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 502 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 301 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Top (bad) request_uri",
   "type": "table",
   "description": "All request_uri that get a status between the following: 401,403,404,400,500,502,301",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 401 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 403 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 404 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 400 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 500 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 502 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status = 301 [$__interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | line_format \"Request for {{.path}} with HTTP status {{.status}}\""
    }
   ]
  },
  { "title": "Loki Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Log volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}[$__interval]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Top paths",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 118 },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | path != \"\" [$__interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | status >= 500 [$__interval])) / sum(rate({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}[$__interval]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"pertisk-eproxy\",app=\"pertisk-eproxy\",job=~\"$job\",filename=~\"$filename\"}[$__interval]))",
     "legendFormat": "Queries/sec"
    }
   ]
  },
  { "title": "Hub Style", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\",status!~\"(2..|401)\"}[$__range])) / clamp_min(sum(increase(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\",status=~\".+\"}[$__range])), 1)",
     "legendFormat": "Error ratio"
    }
   ]
  },
  {
   "title": "Healthy Upstreams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pertisk_eproxy_upstream_healthy{namespace=\"pertisk-eproxy\"})",
     "legendFormat": "healthy"
    }
   ]
  },
  {
   "title": "Requests by Site",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (site) (rate(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\"}[1m])) > 0",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Requests by Protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (proto) (rate(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\"}[1m])) > 0",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(pertisk_eproxy_site_requests_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\"}[1m])) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(pertisk_eproxy_site_bytes_sent_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\"}[1m]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(rate(pertisk_eproxy_site_bytes_received_total{namespace=\"pertisk-eproxy\",site=~\"$site\",proto=~\"$proto\"}[1m]))",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Upstream Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (upstream_name) (pertisk_eproxy_upstream_connections{namespace=\"pertisk-eproxy\"})",
     "legendFormat": "{{upstream_name}}"
    }
   ]
  }
 ]
}