{
 "title": "PTProxy",
 "tags": [ "Website" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Mode",
    "query": "label_values({job=~\"pertisk-eproxy-(ingress|proxy)\"}, job)"
   },
   {
    "name": "filename",
    "label": "Filename",
    "query": "label_values({job=~\"$job\"}, filename)"
   }
  ]
 },
 "panels": [
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(filename) (count_over_time({job=~\"$job\",filename=~\"$filename\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Visitor per Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | unwrap bytes_sent [$__interval]))"
    }
   ]
  },
  {
   "title": "Request per status code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | response_code != \"\" [$__interval]))",
     "legendFormat": "HTTP status: {{response_code}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | response_code != \"\" [$__interval]))",
     "legendFormat": "status: {{response_code}}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | method != \"\" [$__interval]))",
     "legendFormat": "Method: {{method}}"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(protocol) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | protocol != \"\" [$__interval]))",
     "legendFormat": "Protocol: {{protocol}}"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(compression) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\"  [$__interval]))",
     "legendFormat": "Compression: {{compression}}"
    }
   ]
  },
  {
   "title": "Status in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | response_code != \"\" [$__interval]))",
     "legendFormat": "status: {{response_code}}"
    }
   ]
  },
  {
   "title": "Methods in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | method != \"\" [$__interval]))",
     "legendFormat": "Method: {{method}}"
    }
   ]
  },
  {
   "title": "Browsers in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum by(http_user_agent) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | http_user_agent != \"\" [$__interval]))",
     "legendFormat": "Browser: {{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Top Websites",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum by(authority) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | authority != \"\" [$__interval]))",
     "legendFormat": "{{authority}}"
    }
   ]
  },
  { "title": "Bad requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top (bad) IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 401 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 403 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 404 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 400 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 500 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 502 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    },
    {
     "expr": "sum by(client_ip) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 301 | client_ip != \"\" [$__interval]))",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Top (bad) request_uri",
   "type": "table",
   "description": "All request_uri that get a status between the following: 401,403,404,400,500,502,301",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 401 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 403 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 404 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 400 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 500 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 502 [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code = 301 [$__interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | line_format \"Request for {{.path}} with HTTP response_code {{.response_code}}\""
    }
   ]
  },
  { "title": "Loki Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Log volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\",filename=~\"$filename\"}[$__interval]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Top paths",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 118 },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({job=~\"$job\",filename=~\"$filename\"}| json | __error__=\"\" | path != \"\" [$__interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate({job=~\"$job\",filename=~\"$filename\"} | json | __error__=\"\" | response_code >= 500 [$__interval])) / sum(rate({job=~\"$job\",filename=~\"$filename\"}[$__interval]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Query rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=~\"$job\",filename=~\"$filename\"}[$__interval]))",
     "legendFormat": "Queries/sec"
    }
   ]
  }
 ]
}